# Generated by Django 4.2.27 on 2026-03-15 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0003_remove_publication_conference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', '-cited_by']},
        ),
        migrations.AddField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='graph_app.facultyprofile'),
        ),
        migrations.AddField(
            model_name='publication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cited_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publication',
            name='co_author',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='domains',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='download_links',
            field=models.TextField(blank=True, default=''),
        ),
    ]
